### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Griboedoff** [oisincar/imois.in#6]
Hi.
I really like Travle and I've noticed that you recently added translations, if you interested i can help tune russian wordings that they will sound more natural.
Now it is a bit clunky.
For example "Copy results" button in russian reads as statement "Results of copy action".
![image](https://github.com/oisincar/imois.in/assets/16411561/b87b0968-7da7-4e26-a378-b6ea47f26ee3)

**Comment by oisincar** [comment]
Hi. Sorry for the delay (I didn't expect people to find this repo!)

I hope you've been enjoying the new Russian translations provided by another russian player, if there's any issues with those, let me know!
