### ISSUE TITLE
[travle] French translation improvements

### ISSUE THREAD

**Issue by ygorg** [oisincar/imois.in#7]
Hi, thank you so much for this game. It is a great way to learn about countries (and their connection ;)
I'm a native french speaker so I took the liberty of improving the translation. I tried to keep the same meaning as the english version and shortening the text (english to french can result in very long paraphrases) so it fits similarly on the page.
"guess" is not easy to translate to french, so I tried to use the right words in the right places.
I chose to "vouvoyer" the user (translate "you" to "vous" instead of "tu") which is more polite and creates a distance between the user and author because in my point of view saying "There isn't even a way to get from your guess to the target" can be a bit much !

I'm a computer scientist so I tried my best to replace every accent by the unicode and also keeping the syntax for variable substitution.
Here is my version : [fr.json.txt](https://github.com/oisincar/imois.in/files/12413250/fr.json.txt)

Also, there might be an issue with the escaping single quotes (apostrophe) of the string in `guesses.titleText` : 
```html
<!--It looks like this-->
<span class="align-middle emoji" title="C" est="" une="" bonne="" idée.="" ce="" n'est="" pas="" le="" chemin="" plus="" court,="" mais="" loin.'="">🟧</span>
<!--instead of this-->
<span class="align-middle emoji" title="C'est une bonne idée. Ce n'est pas le chemin le plus court, mais ce n'est pas loin.">🟧</span>
```

**Comment by oisincar** [comment]
This is fantastic, thanks for taking the time to do this! I'll update it shortly.

I'll happily add your name to the credits - How would you like to be credited? (Name, username...?)

P.S. Good spot on guesses.titleText, fixed that too.

**Comment by ygorg** [comment]
Great ! You can use my @ ygorg I guess.

Also I forgot to mention that I added a link to wikipedia for "exclaves" to clear up any misunderstanding because it is really similar to "esclaves" (slaves in english) and with the previous translation it looked like a typo and the meaning was weird.
